# from repo root:
# docker-compose -f .docker/docker_manifest_dev.yaml -p lodging_dev up --build

networks:
  locally:

services:
  rest:
    build:
      context: ../aspnet
      dockerfile: ../.docker/aspnet_local.dockerfile
    depends_on:
      - data
    environment:
      ConnectionStrings__pgsql: 'Host=data;Database=LodgingData;Username=postgres;Password=LodgingData@2020;'
      ConnectionStrings__zipkin: 'http://trace:9411/'
    networks:
      - locally
    ports:
      - 8002:80

  data:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LodgingData@2020
    image: postgres:12
    networks:
      - locally
    ports:
      - 5434:5432

  trace:
    image: openzipkin/zipkin-slim
    networks:
      - locally
    ports:
      - 9413:9411

version: '3.8'
