# from repo root:
# docker-compose -f .docker/docker_manifest.yaml -p lodging up --build

networks:
  locally:

services:
  rest:
    build:
      context: ../aspnet
      dockerfile: ../.docker/aspnet_local.dockerfile
    depends_on:
      - data
    environment:
      ConnectionStrings__pgsql: 'Host=data;Database=LodgingData;Username=admin;Password=admin;'
      ConnectionStrings__zipkin: 'http://trace:9411/'
    networks:
      - locally
    ports:
      - 8002:80

  data:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    image: postgres:12
    networks:
      - locally
    ports:
      - 5433:5432

  trace:
    image: openzipkin/zipkin-slim
    networks:
      - locally
    ports:
      - 9413:9411

version: '3.8'
